name = "SparseFFT"
uuid = "83a9e1f3-fd64-4b3a-8d8f-59aae77cc229"
authors = ["Charlotte Haley <haleycharlotte@gmail.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"] 
